print("Content-Type: text/html")
print()

print ("<html>")
print ("<head>")
print ("<meta charset=\"utf-8\">")
print ("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">")
print ("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
print (" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap\@5.1.0/dist/css/bootstrap.min.css\">")
print ("<link href=\"https://fonts.googleapis.com/css?family=Droid+Sans:400,700\" rel=\"stylesheet\">")
print ("<link rel=\"stylesheet\" href=\"https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css\">")
print ("<link rel=\"stylesheet\" href=\"./assets/css/upload_file.css\">")
print ("<link rel=\"stylesheet\" href=\"./assets/css/form.css\">")
print ("<script src=\"https://code.jquery.com/jquery-1.10.2.js\"></script>")

print ("<title>Perl</title>")
print ("</head>")
print ("<body>")
print ("<div id=\"navbar\"></div>")
print ("<script>$(function(){ \$(\"#navbar\").load(\"navbar.html\"); });</script>")
print ("<div class=\"container gallery-container\">")
print ("<h1>This page is in Python.<h1>")

print ("</div>")

print ("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>")
print ("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js\"></script>")
print ("<script>")
print ("baguetteBox.run('.tz-gallery');")
print ("$(document).ready(function(){")
print ("\$('form input').change(function () {")
print ("\$('form p').text(this.files.length + \" file(s) selected\");")
print ("});")
print ("});")
print ("</script>")
print ("</body>")
print ("</html>")
