all:
	@clang++ BodyMaker.cpp bodyMakerTest.cpp HeaderMaker.cpp HttpCodes.cpp Response.cpp ResponseMaker.cpp ../config_lexer_parser/Config.cpp ../config_lexer_parser/ContextBase.cpp ../config_lexer_parser/Context.cpp ../config_lexer_parser/Lexer.cpp ../config_lexer_parser/ParserConfig.cpp ../config_lexer_parser/Parser.cpp
	@./a.out
	@rm a.out
