name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./config_lexer_parser/
    steps:
      - run: make test

