name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./srcs/config_lexer_parser/
    steps:
      - run: sudo apt install -y clang++
      - run: make test

